version: "3.9"

services:
    scannerapi:
        build: 
            context: API
        image: docker.com/scannerapi-fastapi:latest
        environment:
            LOG_LEVEL: "Debug"
        ports:
            - "9180:80"
        volumes:
            - ./API/app/data:/app/data
        depends_on:
            - mosquitto-server
    mosquitto-server:
        image: eclipse-mosquitto:latest        
        restart: always
        ports:
            - "1883:1883"
        volumes:
            - ./Mosquitto/config:/mosquitto/config